name: DungeonCrusher
version: '${project.version}'
main: de.hannezhd.dungeoncrusher.DungeonCrusher
api-version: '1.20'
author: HanneZHD
commands:
  config:
    tab-completer: true
    description: config funktionen
  pay:
    tab-completer: true
    description: Überweise anderen Spieler geld
  money:
    tab-completer: true
    description: Geld Managment
    aliases: eco
  stats:
    description: Sehe deine Stats
  setup:
    tab-completer: true
    description: Setup Befehl
  build:
    description: Gehe in den Baumodus
  setspawn:
    description: Setzte den Spawn
  spawn:
    description: Teleportiere dich zum Spawn
  test:
  shop:
    description: Öffne den Shop
  upgrades:
    description: Upgrade deine Items
    aliases: [upgrade, levelup]
  customgui: